version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: interview-helper-api
    container_name: interview-helper-api
    restart: unless-stopped
    ports:
      - "5500:5500"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5500
      - DATABASE_URL=mongodb://mongodb:27017/interview-helper
      - API_URL=http://localhost:5500
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-your_jwt_refresh_secret_key}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-30d}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE_ENABLED=${LOG_FILE_ENABLED:-true}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-logs/app.log}
    volumes:
      - api_logs:/app/logs
    networks:
      - interview-helper-network

  mongodb:
    image: mongo:8
    container_name: interview-helper-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - interview-helper-network
    command: ["--bind_ip_all"]

volumes:
  api_logs:
  mongodb_data:

networks:
  interview-helper-network:
    driver: bridge
